# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DecimalField(decimal_places=10, max_digits=10)),
                ('event', models.CharField(max_length=500)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blelog.Device')),
            ],
        ),
    ]
