# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blelog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='Undefined_name', max_length=80),
        ),
    ]
