# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blelog', '0002_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
